FROM ubuntu:20.04 AS build

RUN apt-get update -q && apt-get install -yq curl locales
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV HOME=/root

RUN apt-get update -q && apt-get install -yq build-essential git unzip autoconf libncurses5-dev libssl-dev python

WORKDIR /app

RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
ENV PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"
RUN echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc

COPY .tool-versions ./
RUN cat .tool-versions | awk '{print $1}' | xargs -n 1 asdf plugin add
RUN asdf install

RUN mix local.hex --force && \
    mix local.rebar --force

ENV MIX_ENV=test
ENV SECRET_KEY_BASE=nokey

COPY mix.exs mix.lock ./
COPY config config

RUN mix do deps.get, deps.compile

# build assets
COPY assets/package.json assets/package-lock.json ./assets/
RUN npm --prefix ./assets ci --progress=false --no-audit --loglevel=error

COPY priv priv
COPY assets assets

COPY lib lib

RUN npm run --prefix ./assets deploy
RUN mix phx.digest

# compile and build release
COPY test test
COPY native native
COPY script script
COPY .formatter.exs .formatter.exs
COPY .credo.exs .credo.exs
RUN mix compile
CMD ./script/test
