#!/bin/bash

set -eu pipefail

mix deps.get --only prod
MIX_ENV=prod mix compile &&
npm run deploy --prefix ./assets &&
mix phx.digest.clean &&
mix phx.digest &&
MIX_ENV=prod mix release --overwrite &&
rsync -r _build/prod/rel/regex_help ronald:~/srv/

echo "Files copied. Now SSH to the erver and do"
echo "~/srv/regex_help/bin/regex_help restart"