[package]
name = "regexhelper"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "regexhelper"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
regex = "1"
rustler = {git = "git://github.com/rusterlium/rustler.git", branch="master"}
grex = "1.3.0"
