[package]
name = "regexhelper"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "regexhelper"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
regex = "1"
rustler = "0.26.0"
grex = "1.4.0"
