on: push

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker test image
        run: docker build -t regex-help-test -f Dockerfile.test .
      - name: run tests
        run: docker run regex-help-test
