on: push

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Run tests
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@fix-yaml-parsing
        with:
          username: maciejgryka
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: regex-help-test
          dockerfile: Dockerfile
          build_extra_args: "--target test"

      - name: Run tests
        run: docker run docker.pkg.github.com/maciejgryka/regex_help/regex-help-test

  qa-up:
    runs-on: ubuntu-latest
    name: Scale up QA
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        with:
          args: "--config fly.qa.toml scale count 1"
      # repeat, because flyctl doesn't always work as it shouild and the call is indempotent
      - uses: superfly/flyctl-actions@master
        with:
          args: "--config fly.qa.toml scale count 1"

  deploy-qa:
    runs-on: ubuntu-latest
    name: Deploy to QA
    needs: qa-up
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        with:
          args: "deploy --remote-only --config fly.qa.toml --dockerfile Dockerfile"

  test-rf:
    runs-on: ubuntu-latest
    name: Run Rainforest tests
    needs: [unit-test, deploy-qa, qa-up]
    container: gcr.io/rf-public-images/rainforest-cli
    steps:
      - run: rainforest-cli run --run-group-id 8873 --fail-fast --token ${{ secrets.RAINFOREST_API_TOKEN }} --description "regex.help:$GITHUB_REF" --release "$GITHUB_SHA"

  qa-down:
    runs-on: ubuntu-latest
    name: Scale down QA
    needs: test-rf
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        with:
          args: "--config fly.qa.toml scale count 0"
      - uses: superfly/flyctl-actions@master
        with:
          args: "--config fly.qa.toml scale count 0"

  deploy-prd:
    runs-on: ubuntu-latest
    name: Deploy to prod
    env:
      MIX_ENV: prod
    needs: test-rf
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        with:
          args: "deploy --remote-only --config fly.toml --dockerfile Dockerfile"
