on: push

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Run tests
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@fix-yaml-parsing
        with:
          username: maciejgryka
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: regex-help-test
          dockerfile: Dockerfile.test

      - name: Run tests
        run: docker run docker.pkg.github.com/maciejgryka/regex_help/regex-help-test

  deploy-stg:
    runs-on: ubuntu-latest
    name: Deploy to staging
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile"

  stg-up:
    runs-on: ubuntu-latest
    name: Scale up staging
    needs: deploy-stg
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "--config fly.staging.toml scale count 1 --verbose"

  test-rf:
    runs-on: ubuntu-latest
    name: Run Rainforest tests
    needs: [unit-test, deploy-stg, stg-up]
    container: gcr.io/rf-public-images/rainforest-cli
    steps:
      - run: rainforest-cli run --run-group-id 8873 --fail-fast --token ${{ secrets.RAINFOREST_API_TOKEN }} --description "regex.help:$GITHUB_REF" --release "$GITHUB_SHA"

  stg-down:
    runs-on: ubuntu-latest
    name: Scale down staging
    needs: test-rf
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "--config fly.staging.toml scale count 0 --verbose"

  deploy-prd:
    runs-on: ubuntu-latest
    name: Deploy to prod
    env:
      MIX_ENV: prod
    needs: test-rf
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --remote-only --config fly.toml --dockerfile Dockerfile"
