on: push

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Run tests
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@fix-yaml-parsing
        with:
          username: maciejgryka
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: regex-help-test
          dockerfile: Dockerfile.test

      - name: Run tests
        run: docker run docker.pkg.github.com/maciejgryka/regex_help/regex-help-test

  deploy:
    name: Deploy to fly
    env:
      MIX_ENV: prod
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --remote-only"
