on: push

env:
  MIX_ENV: "test"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@fix-yaml-parsing
        with:
          username: maciejgryka
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: regex-help-test
          dockerfile: Dockerfile.test

      - name: Run tests
        run: docker run docker.pkg.github.com/maciejgryka/regex_help/regex-help-test
